version: '3'
services:
  resty:
    container_name: html-nginx
    image: resty-doxygen
    ports:
      - "8081:8080"
    volumes:
      - ./lua_scripts:/opt/lua_scripts
      - output_data:/opt/output

volumes:
  output_data: